GuitarRental/Controllers/GuitarController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GuitarRental.Models;
using GuitarRental.Data;
using Microsoft.AspNetCore.Authorization;
using GuitarRental.Filters;

namespace ASPNETtestprojectControllers
{
    [DisableBasicAuthentication]
    public class GuitarController : Controller
    {
        private ICRUDGuitarRepository guitars;
        private readonly AppDbContext _db;

        public GuitarController(ICRUDGuitarRepository guitars, AppDbContext db)
        {
            this.guitars = guitars;
            _db = db;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Authorize]
        public IActionResult AddForm()
        {
            return View();
        }
        [Authorize]
        public IActionResult List()
        {
            return View(guitars.FindAll());
        }
        [Authorize]
        public IActionResult Details(int id)
        {
            return View(guitars.FindById(id));
        }
        [HttpPost]
        [Authorize]
        public IActionResult Add(Guitar guitar)
        {
            if (ModelState.IsValid)
            {
                guitar = guitars.Add(guitar);
                return View("Confirm", guitar);
            }
            return View("AddForm");
        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            return View(guitars.FindById(id));
        }
        [HttpPost]
        [Authorize]
        public IActionResult Edit(Guitar guitar)
        {
            if (ModelState.IsValid)
            {
                guitar = guitars.Update(guitar);
                return View("List", guitars.FindAll());
            }
            return View();
        }
        [Authorize]
        public IActionResult Delete(int id)
        {
            guitars.Delete(id);
            return View("List", guitars.FindAll());
        }
        public IActionResult FindById(int id)
        {
            return View("List", guitars.FindById(id));
        }
        [Authorize]
        public IActionResult Update(Guitar guitar)
        {
            if (ModelState.IsValid)
            {
                guitar = guitars.Update(guitar);
                return View("List", guitars.FindAll());
            }
            return View();
        }
    }
}

GuitarRental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Guitar" asp-action="Index">Wypożyczalnia gitar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Guitar" asp-action="Index">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Guitar" asp-action="List">Zobacz gitary</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Guitar" asp-action="AddForm"> Dodaj gitarę </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login"> Zaloguj się </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Logout"> Wyloguj się </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-dark border-top footer text-white-50">
        <div class="container">
            <b>&copy; Wypożyczalnia gitar - projekt</b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>